name: Tibia Level Tracker

on:
  schedule:
    - cron: "0 9 * * *"   # 09:00 UTC = 03:00 AM America/Mexico_City
  workflow_dispatch:

permissions:
  contents: read  # no hacemos push

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper -> Supabase
        run: python scripts/scrape_tibia.py
